{
  "swagger" : "2.0",
  "info" : {
    "description" : "ThrowIt Api",
    "version" : "1.0.0",
    "title" : "throwIt"
  },
  "host" : "th.dev",
  "basePath" : "/api",
  "tags" : [ {
    "name" : "Users",
    "description" : "Manage users"
  }, {
    "name" : "Locations manager",
    "description" : "Get countries, states and cities lists"
  } ],
  "schemes" : [ "http" ],
  "consumes" : [ "application/json" ],
  "produces" : [ "application/json" ],
  "paths" : {
    "/user/login" : {
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "Logs user into the system",
        "operationId" : "loginUser",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "description" : "The email/password",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/userLogin"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "type" : "string"
            }
          },
          "400" : {
            "description" : "Invalid username/password supplied"
          }
        }
      }
    },
    "/user/logout" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Logs out current logged in user session",
        "operationId" : "logoutUser",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "default" : {
            "description" : "successful operation"
          }
        },
        "security" : [ {
          "Bearer" : [ ]
        } ]
      }
    },
    "/user/password/forget" : {
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "Logs user into the system",
        "operationId" : "passwordForget",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "email",
          "description" : "User email",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/userEmail"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "type" : "string"
            }
          },
          "400" : {
            "description" : "Invalid email supplied"
          }
        }
      }
    },
    "/user/password/reset" : {
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "Logs user into the system",
        "operationId" : "passwordReset",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "email",
          "description" : "User email",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/resetPassword"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "type" : "string"
            }
          },
          "400" : {
            "description" : "Invalid email supplied"
          }
        }
      }
    },
    "/user/first-step" : {
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "User first step",
        "operationId" : "UserFirstStep",
        "parameters" : [ {
          "in" : "body",
          "name" : "email",
          "description" : "User email",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/userEmail"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "User created",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200"
            }
          },
          "400" : {
            "description" : "Bad Request"
          },
          "402" : {
            "description" : "User already exists"
          }
        }
      }
    },
    "/user/registration" : {
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "User registration",
        "operationId" : "UserRegister",
        "parameters" : [ {
          "in" : "body",
          "name" : "user",
          "description" : "User informations",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/userRegister"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "User created",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_1"
            }
          },
          "400" : {
            "description" : "Bad Request"
          }
        }
      }
    },
    "/get-countries" : {
      "get" : {
        "tags" : [ "Locations manager" ],
        "summary" : "Get countries list",
        "operationId" : "getCountriesList",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "Countries list",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_2"
            }
          },
          "400" : {
            "description" : "Bad Request"
          }
        },
        "security" : [ {
          "Bearer" : [ ]
        } ]
      }
    },
    "/get-countries/{id}" : {
      "get" : {
        "tags" : [ "Locations manager" ],
        "summary" : "Get states list by country id",
        "operationId" : "getCountryStates",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "Country id",
          "required" : true,
          "type" : "integer"
        } ],
        "responses" : {
          "200" : {
            "description" : "States list",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_3"
            }
          },
          "400" : {
            "description" : "Country not found"
          }
        },
        "security" : [ {
          "Bearer" : [ ]
        } ]
      }
    },
    "/get-states/{id}" : {
      "get" : {
        "tags" : [ "Locations manager" ],
        "summary" : "Get cities list by state id",
        "operationId" : "getStatesCities",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "State id",
          "required" : true,
          "type" : "integer"
        } ],
        "responses" : {
          "200" : {
            "description" : "Cities list",
            "schema" : {
              "$ref" : "#/definitions/inline_response_200_4"
            }
          },
          "400" : {
            "description" : "Country not found"
          }
        },
        "security" : [ {
          "Bearer" : [ ]
        } ]
      }
    }
  },
  "securityDefinitions" : {
    "Bearer" : {
      "description" : "For accessing the API a valid JWT token must be passed in all the queries in\nthe 'Authorization' header.\n\n\nA valid JWT token is generated by the API and retourned as answer of a call\nto the route /login giving a valid user & password.\n\n\nThe following syntax must be used in the 'Authorization' header :\n\n    Bearer: xxxxxx.yyyyyyy.zzzzzz\n",
      "type" : "apiKey",
      "name" : "Authorization",
      "in" : "header"
    }
  },
  "definitions" : {
    "userLogin" : {
      "type" : "object",
      "properties" : {
        "email" : {
          "type" : "string",
          "description" : "User email"
        },
        "password" : {
          "type" : "string",
          "description" : "User email"
        }
      }
    },
    "userEmail" : {
      "type" : "object",
      "properties" : {
        "email" : {
          "type" : "string",
          "description" : "User email"
        }
      }
    },
    "resetPassword" : {
      "type" : "object",
      "properties" : {
        "email" : {
          "type" : "string",
          "description" : "User email"
        },
        "password" : {
          "type" : "string",
          "description" : "User password"
        },
        "confirmPassword" : {
          "type" : "string",
          "description" : "User password confirmation"
        },
        "token" : {
          "type" : "string",
          "description" : "reset token"
        }
      }
    },
    "userFirstStepResponse" : {
      "type" : "object",
      "properties" : {
        "email" : {
          "type" : "string",
          "description" : "User email"
        },
        "id" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "User id"
        }
      },
      "example" : {
        "id" : 0,
        "email" : "email"
      }
    },
    "userRegister" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int64"
        },
        "userName" : {
          "type" : "string"
        },
        "firstName" : {
          "type" : "string"
        },
        "lastName" : {
          "type" : "string"
        },
        "email" : {
          "type" : "string"
        },
        "password" : {
          "type" : "string"
        },
        "birthDate" : {
          "type" : "string",
          "format" : "datetime"
        },
        "city" : {
          "type" : "integer",
          "format" : "int32"
        },
        "avatar" : {
          "type" : "integer",
          "format" : "int32"
        }
      }
    },
    "user" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int64"
        },
        "userName" : {
          "type" : "string"
        },
        "firstName" : {
          "type" : "string"
        },
        "lastName" : {
          "type" : "string"
        },
        "email" : {
          "type" : "string"
        },
        "password" : {
          "type" : "string"
        },
        "birthDate" : {
          "type" : "string",
          "format" : "datetime"
        },
        "country" : {
          "type" : "string"
        },
        "city" : {
          "type" : "string"
        },
        "avatar" : {
          "type" : "string"
        }
      },
      "example" : {
        "firstName" : "firstName",
        "lastName" : "lastName",
        "country" : "country",
        "password" : "password",
        "city" : "city",
        "id" : 0,
        "avatar" : "avatar",
        "userName" : "userName",
        "birthDate" : "birthDate",
        "email" : "email"
      }
    },
    "statesByCountryId" : {
      "type" : "object",
      "properties" : {
        "ID" : {
          "type" : "integer",
          "format" : "int32"
        },
        "states" : {
          "$ref" : "#/definitions/statesByCountryId_states"
        }
      },
      "example" : {
        "ID" : 0,
        "states" : {
          "data" : [ {
            "ID" : 6,
            "Name" : "Name"
          }, {
            "ID" : 6,
            "Name" : "Name"
          } ]
        }
      }
    },
    "citiesByStateId" : {
      "type" : "object",
      "properties" : {
        "ID" : {
          "type" : "integer",
          "format" : "int32"
        },
        "cities" : {
          "$ref" : "#/definitions/citiesByStateId_cities"
        }
      },
      "example" : {
        "cities" : {
          "data" : [ {
            "ID" : 6,
            "Name" : "Name"
          }, {
            "ID" : 6,
            "Name" : "Name"
          } ]
        },
        "ID" : 0
      }
    },
    "countries" : {
      "type" : "object",
      "properties" : {
        "ID" : {
          "type" : "integer",
          "format" : "int32"
        },
        "Name" : {
          "type" : "string"
        },
        "Code" : {
          "type" : "string"
        }
      },
      "example" : {
        "ID" : 0,
        "Code" : "Code",
        "Name" : "Name"
      }
    },
    "states" : {
      "type" : "object",
      "properties" : {
        "ID" : {
          "type" : "integer",
          "format" : "int32"
        },
        "Name" : {
          "type" : "string"
        }
      },
      "example" : {
        "ID" : 6,
        "Name" : "Name"
      }
    },
    "cities" : {
      "type" : "object",
      "properties" : {
        "ID" : {
          "type" : "integer",
          "format" : "int32"
        },
        "Name" : {
          "type" : "string"
        }
      },
      "example" : {
        "ID" : 6,
        "Name" : "Name"
      }
    },
    "inline_response_200" : {
      "properties" : {
        "data" : {
          "$ref" : "#/definitions/userFirstStepResponse"
        }
      },
      "example" : {
        "data" : {
          "id" : 0,
          "email" : "email"
        }
      }
    },
    "inline_response_200_1" : {
      "properties" : {
        "data" : {
          "$ref" : "#/definitions/user"
        }
      },
      "example" : {
        "data" : {
          "firstName" : "firstName",
          "lastName" : "lastName",
          "country" : "country",
          "password" : "password",
          "city" : "city",
          "id" : 0,
          "avatar" : "avatar",
          "userName" : "userName",
          "birthDate" : "birthDate",
          "email" : "email"
        }
      }
    },
    "inline_response_200_2" : {
      "properties" : {
        "data" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/countries"
          }
        }
      },
      "example" : {
        "data" : [ {
          "ID" : 0,
          "Code" : "Code",
          "Name" : "Name"
        }, {
          "ID" : 0,
          "Code" : "Code",
          "Name" : "Name"
        } ]
      }
    },
    "inline_response_200_3" : {
      "properties" : {
        "data" : {
          "$ref" : "#/definitions/statesByCountryId"
        }
      },
      "example" : {
        "data" : {
          "ID" : 0,
          "states" : {
            "data" : [ {
              "ID" : 6,
              "Name" : "Name"
            }, {
              "ID" : 6,
              "Name" : "Name"
            } ]
          }
        }
      }
    },
    "inline_response_200_4" : {
      "properties" : {
        "data" : {
          "$ref" : "#/definitions/citiesByStateId"
        }
      },
      "example" : {
        "data" : {
          "cities" : {
            "data" : [ {
              "ID" : 6,
              "Name" : "Name"
            }, {
              "ID" : 6,
              "Name" : "Name"
            } ]
          },
          "ID" : 0
        }
      }
    },
    "statesByCountryId_states" : {
      "properties" : {
        "data" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/states"
          }
        }
      },
      "example" : {
        "data" : [ {
          "ID" : 6,
          "Name" : "Name"
        }, {
          "ID" : 6,
          "Name" : "Name"
        } ]
      }
    },
    "citiesByStateId_cities" : {
      "properties" : {
        "data" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/cities"
          }
        }
      },
      "example" : {
        "data" : [ {
          "ID" : 6,
          "Name" : "Name"
        }, {
          "ID" : 6,
          "Name" : "Name"
        } ]
      }
    }
  }
}